# Dependabot configuration file with limited notifications

version: 2
updates:
  # Update Python packages - Monthly to reduce emails
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"
    assignees:
      - "TurboRx"
    # Group all updates together to reduce notifications
    groups:
      python-packages:
        patterns:
          - "*"

  # Update Node.js packages - Monthly to reduce emails
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "npm"
      include: "scope"
    # Group all updates together to reduce notifications
    groups:
      javascript-packages:
        patterns:
          - "*"

  # Update GitHub Actions - Quarterly to reduce emails
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    # Group all updates together to reduce notifications
    groups:
      github-actions:
        patterns:
          - "*"