version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
    commit-message:
      prefix: pip
    groups:
      python-packages:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: npm
    groups:
      javascript-packages:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: github-actions
    groups:
      actions:
        patterns:
          - "*"
